### ISSUE TITLE
Modify contacts table structure

### ISSUE THREAD

**Issue by renggasaksono** [arbuuuud/gnt-aops#21]
#18 Apakah sebaiknya untuk beberapa field dikasih default value? Seperti active = 1, isAuotomaticFollowUp  = 1

Untuk lastFollowUp bisa dibuat Null saja default nya mungkin.

Untuk provinsi ada 2 field, State dan Province. Mungkin salah satu bisa di remove.

**Comment by arbuuuud** [comment]
boleh saja ceng..
tapi lastfollowup dibuat date now saja..

province dan state boleh saja di bikin satu ceng..
